In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/zakiyff/crescent-moon-visibility-dataset-icop-derived/Crescent_Moon_Visibility_Dataset_(ICOP_Derived).csv
/kaggle/input/datasets/zakiyff/crescent-moon-visibility-dataset-icop-derived/Crescent_Moon_Visibility_Dataset_(ICOP_Derived).xlsx

In [2]:
df = pd.read_csv("/kaggle/input/datasets/zakiyff/crescent-moon-visibility-dataset-icop-derived/Crescent_Moon_Visibility_Dataset_(ICOP_Derived).csv")

In [3]:
df.head()

,date,country,visible,weather,observ,hijri_month,hijri_year,source
0,2013-03-12,Algeria,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en
1,2013-03-12,Indonesia,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en
2,2013-03-12,Indonesia,0,hazy,2 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en
3,2013-03-12,Iran,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en
4,2013-03-12,Iran,1,clear,2 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en

In [4]:
import re
def extract_city(text):
    text = text.lower()
    
    match = re.search(r'from (.*?) city', text)
    if match:
        return match.group(1).strip().title()
    
    return None

In [5]:
df['city'] = df['observ'].apply(extract_city)

In [6]:
df.head(20)

,date,country,visible,weather,observ,hijri_month,hijri_year,source,city
0,2013-03-12,Algeria,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Ghardaia
1,2013-03-12,Indonesia,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Medan
2,2013-03-12,Indonesia,0,hazy,2 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Surakarta
3,2013-03-12,Iran,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Bojnord
4,2013-03-12,Iran,1,clear,2 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Esfahan
5,2013-03-12,Nigeria,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Kaduna
6,2013-03-12,Nigeria,0,hazy,2 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Kaduna
7,2013-03-12,Oman,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Al-Fulaij
8,2013-03-12,Pakistan,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Karachi
9,2013-03-12,Saudi Arabia,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Riyadh
10,2013-03-12,South Africa,0,clear,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Cape Town
11,2013-03-12,Tunisia,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,المنستير
12,2013-03-12,United Arab Emirates,0,clear,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,أبوظبي
13,2013-03-12,United Arab Emirates,0,clear,2 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Dubai
14,2013-03-12,United Arab Emirates,1,clear,3 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Abu Dhabi
15,2013-03-12,United Kingdom,0,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,York
16,2013-03-12,United States,1,cloudy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Blacksburg
17,2013-03-13,Indonesia,1,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Medan
18,2013-03-13,Indonesia,0,hazy,2 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Surakarta
19,2013-03-13,Malaysia,1,hazy,1 . Time of observation: After ...,Jumadal Al-Aula,1434,https://astronomycenter.net/icop/jua34.html?l=en,Tg. Bidara

In [7]:
pd.set_option('display.max_rows', None)
print(df['city'].value_counts())

city
Surakarta                                             251
Blacksburg                                            240
Shahreza                                              188
York                                                  155
بنسليمان                                              131
Munich                                                116
ديربلوط                                               110
Cape Town                                              98
Dhaka                                                  96
عيسى                                                   88
Kaduna                                                 86
كوينين                                                 82
Bauchi                                                 81
طنجة                                                   74
طرابلس                                                 68
Accra                                                  68
Ghardaia                                               66
Medan                                                  65
Sydney                                                 61
دبي                                                    59
Karachi                                                57
المهدية                                                55
تاوريرت                                                53
الناظور                                                48
Sarajevo                                               47
القاهرة                                                45
Daressalaam                                            45
الإمارات                                               44
المدينة المنورة                                        44
Abu Dhabi                                              43
Esfahan                                                39
باتنة                                                  38
Kathmandu                                              34
قمار                                                   33
المنستير                                               32
جدة                                                    32
Ilorin                                                 32
قم                                                     32
Tucson                                                 32
Al-Fulaij Observatory                                  31
Ako                                                    30
حمام الأنف                                             30
Moerlenbach                                            29
Muscat                                                 29
البريقة                                                28
Tanjung Bidara                                         28
بريان                                                  25
الزرقاء                                                25
Tamale                                                 25
Ponorogo                                               25
Sewerqia                                               24
انواكشوط                                               24
Telok Kemang Observatory, Port Dickson                 23
Bolton                                                 23
الكويف                                                 23
Amman                                                  23
الموصل                                                 22
Borella                                                22
Colombo                                                22
Telok Kemang Observatory                               21
جعيمة                                                  20
Dammam                                                 20
Boraydah                                               20
القدس                                                  19
مدينة الصدر                                            19
Tabriz                                                 19
Riyadh                                                 19
Al-Fulaij                                              18
Mcdonald Obs                                           18
Buraydah                                               18
أملج                                                   18
‏لورنس Lawrence                                        17
الظهران                                                17
عمان                                                   17
Abha                                                   17
Milan                                                  16
Bandar Seri Begawan                                    16
Mulhouse                                               16
بغداد الجديدة                                          16
سطيف                                                   15
Port Dickson                                           15
Lagos                                                  15
الرباح                                                 14
طنطا                                                   14
ڤمار                                                   14
Dakar                                                  14
المحمدية                                               14
الكويت                                                 14
بريدة                                                  14
حاسي بحبح                                              13
Irbid                                                  13
الرباط                                                 13
Brisbane                                               13
M6                                                     13
بنها                                                   13
مدينة عيسى                                             12
مصر                                                    12
Dhahran                                                12
شبام                                                   12
معسكر                                                  12
Ikorodu                                                12
Colombo04                                              12
مغنية                                                  12
الصدر                                                  11
Colombo-04                                             11
اربد                                                   11
Tolna                                                  11
نواكشوط                                                11
Khatim                                                 11
الهفوف                                                 11
صفط اللبن                                              10
Cunupia                                                10
Bukit Agok                                             10
Perth                                                  10
Tripoli                                                10
Tirana                                                 10
Melbourne                                              10
Slough                                                 10
Halat Ammar                                            10
أڤمار                                                  10
Tirane                                                  9
ڨمار                                                    9
حلب                                                     9
معرة مصرين                                              9
عجاجة                                                   9
Sokoto                                                  9
برج عمر ادريس                                           9
Basrah                                                  9
البصرة                                                  9
الخليل                                                  9
Bojnord                                                 9
Oslo                                                    9
إربد                                                    8
برج عمر إدريس                                           8
Tg Bidara                                               8
Abuja                                                   8
Al-Fulaij Obseravtory                                   8
Dubai                                                   8
Teluk Kemang                                            8
Barika                                                  8
مهریز                                                   8
Rotterdam                                               7
Doha                                                    7
Makkah                                                  7
Al Basrah                                               7
London                                                  7
وجدة                                                    7
Bataszek                                                7
بعلبك                                                   7
Douala                                                  7
Garoowe                                                 7
Melilla                                                 7
السويرقيه                                               7
Al-Khoudh                                               7
مرصد الفليج                                             7
Tanger                                                  7
تاجوراء                                                 7
Houston                                                 7
بني يزقن                                                7
القرارة                                                 6
Christiansburg                                          6
Marburg                                                 6
بوسعادة                                                 6
Jasin                                                   6
Barus                                                   6
نزوى                                                    6
المدية                                                  6
Kuala Tutong                                            6
الدمام                                                  6
وزان                                                    6
دير بلوط                                                6
املج                                                    5
Marawi                                                  5
عسير                                                    5
Guerrara                                                5
الحسينية                                                5
Lakemba                                                 5
Calgary                                                 5
Clermont Ferrand                                        5
Saravan                                                 5
الجيزة                                                  5
تمارة                                                   5
Taourirt                                                5
New Delhi                                               5
بئر ربعة شمال                                           5
عين فكرون                                               5
Musaffah                                                5
Hafeet Mountain                                         5
مقيبلة                                                  5
الرياض                                                  5
Taft                                                    5
Beirut                                                  5
Labuan                                                  5
جبل حفيت                                                4
عجمان                                                   4
Sakarya                                                 4
Mörlenbach                                              4
Baku                                                    4
ابوكبير                                                 4
Hamm                                                    4
بريـــدة                                                4
الدار البيضاء                                           4
Almadina                                                4
Toulon                                                  4
Richmond                                                4
Zaragoza                                                4
Roanoke                                                 4
Curepipe                                                4
شط العرب                                                4
جبل نزوى                                                4
: 40 Kilometer From Shahreza To Semiram Road (Gard      4
Gainesville                                             4
برادفورد Bradford                                       4
غرداية                                                  4
Semenyih                                                4
لورنس Lawrence                                          4
Tutong                                                  4
كاتماندو                                                4
Mosul                                                   3
Sandvika                                                3
Tg. Bidara                                              3
أبوظبي                                                  3
العطف                                                   3
عمّان                                                   3
تملالت                                                  3
جبل جيس                                                 3
العبدلي                                                 3
Fayetteville                                            3
40 Kilometer From Shahreza To Semiram Road (Gardan      3
Sadus                                                   3
غريان                                                   3
Stuttgart                                               3
Negombo                                                 3
الوادي                                                  3
شقراء                                                   3
Kirchhain                                               3
Monastir                                                3
العين                                                   3
Weinheim                                                3
Adelaide                                                3
سلوى                                                    3
Mumbai                                                  3
الداخلة                                                 3
مراكش                                                   3
Melaka                                                  3
Wildomar                                                3
سدني                                                    3
Darwin                                                  3
بغداد                                                   3
Kesang Jaya                                             3
Lembang                                                 3
سلا                                                     3
Zanzibar                                                3
Leeds                                                   3
Agege                                                   3
Sour                                                    3
Mannheim                                                3
Keriam                                                  3
جيزان                                                   3
السلیمانیه                                              3
La Rochelle                                             3
سكاكا                                                   3
Kupang                                                  3
Benslimane                                              3
بني جمرة                                                3
البرمة                                                  3
الدوحة                                                  3
الأحساء                                                 3
ثمريت                                                   3
البصر                                                   3
Jabal Hafeet                                            3
Oujda                                                   2
النجف الاشرف                                            2
Alfegra                                                 2
الخبر                                                   2
Jabal Khandamah                                         2
Miri                                                    2
Albosor                                                 2
Margate                                                 2
خمینی شهر                                               2
بني يزجن - جبل عبد الدايم                               2
الشرق                                                   2
Bhamdoun                                                2
Hammam Lif                                              2
مسلاتة                                                  2
Ludwigshafen Am Rhein                                   2
Jabal Shams                                             2
Sohar                                                   2
E73                                                     2
23 Kilometers Far From Dehaghan To Borujen              2
Valencia                                                2
Baghdad                                                 2
بوجدور                                                  2
ينبع الصناعية                                           2
Debrecen                                                2
السلط                                                   2
Blackburg                                               2
Rüsselsheim                                             2
المدينة                                                 2
Thirsk                                                  2
Tabouk                                                  2
أرفود                                                   2
Selsey                                                  2
جده                                                     2
سيئون                                                   2
Kisszallas                                              2
البلديات                                                2
Poodeh Village Cemetery                                 2
Yibal Khuff                                             2
‏ ‏لورنس Lawrence                                       2
Sarıyer                                                 2
وادي رم                                                 2
Shawa                                                   2
Delhi                                                   2
جبل عبد الدايم                                          2
الممدية                                                 2
Alhara                                                  2
إفران                                                   2
العالوك                                                 2
Near Boraydah                                           2
المزة                                                   2
Tapanuli Tengah                                         2
وهران                                                   2
تافيلالت - بني يزجن                                     2
Mashhad                                                 2
Tehran                                                  2
Eastlondon                                              2
Colombo 03                                              2
Canberra                                                2
Fleetwood                                               2
جزيرة مصيرة                                             2
ورقلة                                                   2
Hunstanton                                              2
Tsukuba                                                 2
Oshodi                                                  2
صور                                                     2
Agok Hill                                               2
Johor Bahru                                             2
الخرطوم                                                 2
Boraidah                                                2
Madinah                                                 2
Cece                                                    2
Ghaba                                                   2
40 Kilometers Far From Shahreza To Semirom Called       2